version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:5000/api
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=production
      - MONGO_URI=mongodb://mongo:27017/pathpilot
      - JWT_SECRET_KEY=your-secret-key-here
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000
    depends_on:
      - mongo
      - rasa

  rasa:
    build:
      context: ./rasa_bot
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    volumes:
      - ./rasa_bot:/app
    command: run --enable-api --cors "*"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 